import { error, json } from '@sveltejs/kit';
import type { RequestHandler } from './$types';

export const GET: RequestHandler = async ({ params }) => {
  const { projectId } = params;

  if (!projectId) {
    throw error(400, 'Project ID is required');
  }

  const today = new Date().toISOString().split('T')[0];
  const dateStr = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const pdfBuffer = await generateInspectionPdf(projectId, dateStr);

  return new Response(pdfBuffer, {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="inspection-summary-${projectId}-${today}.pdf"`,
    },
  });
};

async function generateInspectionPdf(projectId: string, dateStr: string): Promise<Uint8Array> {
  const { PDFDocument, StandardFonts, rgb } = await import('pdf-lib');

  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);

  let page = doc.addPage([595.28, 841.89]);
  const { width, height } = page.getSize();

  let y = height - 50;

  function addText(
    text: string,
    size: number,
    opts: { bold?: boolean; color?: [number, number, number] } = {},
  ) {
    page.drawText(text, {
      x: 50,
      y,
      size,
      font: opts.bold ? bold : font,
      color: opts.color ? rgb(...opts.color) : rgb(0.15, 0.15, 0.15),
    });
    y -= size * 1.5;
  }

  function checkPage() {
    if (y < 100) {
      page = doc.addPage([595.28, 841.89]);
      y = height - 50;
    }
  }

  addText('SiteSync Pro', 24, { bold: true, color: [0.2, 0.4, 0.8] });
  addText('Daily Inspection Summary', 18, { bold: true });
  addText(dateStr, 12);
  addText('', 12);
  addText(`Project: ${projectId}`, 12);
  addText('─'.repeat(70), 10);

  addText('', 12);
  addText('Inspections Completed Today', 16, { bold: true });
  addText('No inspection data available. Connect a Convex deployment to see live data.', 10);
  addText('', 12);

  addText('─'.repeat(70), 10);
  addText('', 12);
  addText('Summary', 16, { bold: true });
  addText('This report is auto-generated by SiteSync Pro.', 10);
  addText(`Generated: ${new Date().toISOString()}`, 10);

  return await doc.save();
}
