apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sitesync-web
  namespace: sitesync
  labels:
    app: sitesync-web
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sitesync-web
